### PR TITLE
[#289] Fix POJO mapping for inherited classes

### PR DESCRIPTION
**Pull request by fbiville**
This PR might not be merge-able yet as there may be another bug yet to be discussed.

### CODE REVIEW

**Comment by jexp** [comment]
What is the other bug @fbiville ?

**Comment by fbiville** [comment]
Not sure if a bug or not, but I've defined in this (ignored bc failing) test 2 POJO :

 * ParentPojo
 * ConflictingPojo (extends ParentPojo)

Both have a field name `a` but mapped differently (`ParentPojo` annotates `@ResultColumn("a")`, `ConflictingPojo` annotates @ResultColumn("a_bis").

I give the following input:
```
  a => 23
  a_bis => "23"
```

I expect: 
 * `ParentPojo` "a" field (an `Integer`) to be mapped to `23`
 * `ConflictingPojo` "a" field (a `String`) to be mapped to `"23"`

As far as I remember, `ConflictingPojo` "a" field is left `null`.
You can "unignore" the test to observe this.

**Comment by jexp** [comment]
Ya field shadowing is evil. I wouldn't bother with that.

Merged separately for 3.3.1

**Comment by fbiville** [comment]
Thanks :)

**Pull request closed without merging**
