### PR TITLE
Add support for Value Expressions for Repository Query methods

### LINKED ISSUE #2954: Add support for value expressions in repository query methods
See https://github.com/spring-projects/spring-data-commons/pull/3050

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
fixes #2954

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
I've been trying to make this work but I have a couple of tests failing but only when running from Maven

```
[ERROR]   CypherGeneratorTest.shouldCreateRelationshipCreationQueryWithLabelIfPresent:63 expected: <MATCH (startNode:`Entity1`) WHERE startNode.id = $fromId MATCH (endNode) WHERE elementId(endNode) = $toId MERGE (startNode)<-[relProps:`REL`]-(endNode) RETURN elementId(relProps) AS __elementId__> but was: <MATCH (startNode:`Entity1`) WHERE startNode.id = $fromId MATCH (endNode) WHERE elementId(endNode) = $toId MERGE (startNode)<-[relProps:`REL`]-(endNode) RETURN id(relProps) AS __elementId__>
[ERROR]   CypherGeneratorTest.shouldCreateRelationshipCreationQueryWithMultipleLabels:79 expected: <MATCH (startNode:`Entity1`:`MultipleLabel`) WHERE startNode.id = $fromId MATCH (endNode) WHERE elementId(endNode) = $toId MERGE (startNode)<-[relProps:`REL`]-(endNode) RETURN elementId(relProps) AS __elementId__> but was: <MATCH (startNode:`Entity1`:`MultipleLabel`) WHERE startNode.id = $fromId MATCH (endNode) WHERE elementId(endNode) = $toId MERGE (startNode)<-[relProps:`REL`]-(endNode) RETURN id(relProps) AS __elementId__>
[ERROR]   CypherGeneratorTest.shouldCreateRelationshipCreationQueryWithoutUsingInternalIds:99 expected: <MATCH (startNode) WHERE id(startNode) = $fromId MATCH (endNode) WHERE elementId(endNode) = $toId MERGE (startNode)<-[relProps:`REL`]-(endNode) RETURN elementId(relProps) AS __elementId__> but was: <MATCH (startNode) WHERE id(startNode) = $fromId MATCH (endNode) WHERE elementId(endNode) = $toId MERGE (startNode)<-[relProps:`REL`]-(endNode) RETURN id(relProps) AS __elementId__>

```

**Comment by michael-simons** [comment]
I can look at this after my vacation.

**Comment by michael-simons** [comment]
We will look at this, but right now we are a bit time constrained.

**Comment by michael-simons** [comment]
Your branch doesn't even compile:

```
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.366 s
[INFO] Finished at: 2024-10-10T09:26:28+02:00
[INFO] ------------------------------------------------------------------------
[INFO] 10 goals, 10 executed
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (java-compile) on project spring-data-neo4j: Compilation failure: Compilation failure: 
[ERROR] /Users/msimons/Projects/spring-projects/spring-data-neo4j/src/main/java/org/springframework/data/neo4j/repository/query/StringBasedNeo4jQuery.java:[163,54] error: incompatible types: ValueExpressionQueryRewriter cannot be converted to EvaluatingValueExpressionQueryRewriter
[ERROR] /Users/msimons/Projects/spring-projects/spring-data-neo4j/src/main/java/org/springframework/data/neo4j/repository/query/ReactiveStringBasedNeo4jQuery.java:[121,54] error: incompatible types: ValueExpressionQueryRewriter cannot be converted to EvaluatingValueExpressionQueryRewriter
```

🤷

**Review by michael-simons — APPROVED** [review]
Excellent, thank you!

**Pull request merged**
