### PR TITLE
Documentation polishing

### PR DESCRIPTION
**Pull request by fpavageau**
Take 2, on the asciidocs this time.

I've tried to use the code style (for class names) a bit more consistently across the documentation. I've also fixed spelling and grammar issues, mainly after running the documentation through `aspell`.

I've signed the SpringSource CLA in 12/2013.

### CODE REVIEW

**Comment by jexp** [comment]
Hey, @fpavageau would you do me a favor and look at [Spring Data Neo4j 4](https://github.com/spring-projects/spring-data-neo4j/tree/4.0-GA)? We would love some feedback (currently on SNAPSHOT builds as there are some springsource-release issues), see: http://neo4j.com/blog/announcing-spring-data-neo4j-4-0/

Thanks a lot.

**Comment by jexp** [comment]
Merged separately, thanks a lot.

**Comment by fpavageau** [comment]
@jexp It's actually on my todo-list, I wanted to check if an (unreported yet) issue I had in 3.x was still present in 4.0. And try out what's new, of course.

**Comment by jexp** [comment]
4.0 is a complete rewrite from scratch, so everything new, here is a migration guide: 
http://docs.spring.io/spring-data/neo4j/docs/4.0.0.BUILD-SNAPSHOT/reference/html/#migration

**Pull request closed without merging**
